[workspace]
resolver = "2"
members = [
    "procedural_wallpapers",
    "wallpapers"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
