[package]
name = "procedural_wallpapers"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
image = "0.24.2"
clap = { version = "3.2.8", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
