[package]
name = "wallpapers"
version.workspace = true
edition.workspace = true
description = "Procedural Wallpapers Generator - Library"
license-file.workspace = true

[dependencies]
image = "0.25.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
